- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print the loops
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop:
    - Bhavani
    - Lakshmi
    - Krishiv
    - Liyansh